version: 2.1

jobs:
  test:
    parameters:
      jdk-version:
        type: string
      clj-version:
        type: string
    working_directory: ~/project
    docker:
      - image: clojure:temurin-<< parameters.jdk-version>>-noble
    environment:
      CLOJURE_VERSION: << parameters.clj-version >>
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "deps.edn" }}
      - run: clojure -X:test:$CLOJURE_VERSION
      - save_cache:
          paths:
            - ~/.m2
          key: deps-{{ checksum "deps.edn" }}

  deploy:
    working_directory: ~/project
    docker:
      - image: clojure:temurin-8-noble
    steps:
      - checkout
      - run:
         name: Deploy
         command: clojure -T:build deploy :version \"$CIRCLE_TAG\"

run_always: &run_always
  filters:
    branches:
      only: /.*/
    tags:
      only: /.*/

workflows:
  run_all:
    jobs:
      - test:
          matrix:
            parameters:
              jdk-version: ["8", "11", "17", "21", "25"]
              clj-version: ["1.10", "1.11", "1.12"]
          <<: *run_always
      - deploy:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+(-\w+)?/
