version: 2.1

jobs:
  test:
    parameters:
      jdk-version:
        type: string
      clj-version:
        type: string
    working_directory: ~/project
    docker:
      - image: clojure:temurin-<< parameters.jdk-version>>-jammy
    environment:
      CLOJURE_VERSION: << parameters.clj-version >>
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "deps.edn" }}
      - run: clojure -X:test:$CLOJURE_VERSION
      - save_cache:
          paths:
            - ~/.m2
          key: deps-{{ checksum "deps.edn" }}

workflows:
  test_all_jdks:
    jobs:
      - test:
          matrix:
            parameters:
              jdk-version: ["8", "11", "17", "21", "22"]
              clj-version: ["1.10", "1.11", "1.12"]
